version: 2.1

orbs:
  docker: circleci/docker@2.2.0
  sdkman: joshdholtz/sdkman@0.2.0


jobs:
  arm64-native:
    machine:
      image: ubuntu-2004:current
      resource_class: arm.medium
    steps:
      - checkout
      - sdkman/setup-sdkman
      - sdkman/sdkman-install:
          candidate: java
          version: 22.3.r17-grl
      - run:
          name: "bootBuildImage"
          command: "./mvnw clean spring-boot:build-image -Pnative -DskipTests"
          working_directory: Home-Assistant
      - docker/check:
          registry: ghcr.io
          docker-username: amrutprabhu
          docker-password: DOCKER_PASS
      - docker/push:
          image: ghcr.io/amrutprabhu/home-assistant
          tag: $CIRCLE_TAG-aarch_64

workflows:
  arm64-native-workflow:
    jobs:
      - arm64-native:
          context:
            - context
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/