
services:
  ha-listener:
    image: ghcr.io/amrutprabhu/home-assistant-listener:v0.0.0-dirty-aarch_64
    restart: always
    ports:
      - 8080:8080
    environment:
      - token=
      - url=ws://192.168.0.158:8123/api/websocket