name: Native-AMD64

on:
  push:
    tags:
      - "v*"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-java@v2
        with:
          distribution: 'liberica' # See 'Supported distributions' for available options
          java-version: '17'
      - name: Checkout master
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: amrutprabhu
          password: ${{ secrets.TOKEN_SECRET }}

      #Build Image
#      - name: Build Image
#        run: ./mvnw clean spring-boot:build-image -Pnative -DskipTests -Dproject.version=$GITHUB_REF_NAME
#        working-directory: Home-Assistant
      #Tag the version
      #Deploy the image to the Docker registry
      - name: Push Images to Docker Registry
        run: docker push -a ghcr.io/amrutprabhu/home-assistant


  manifest:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: amrutprabhu
          password: ${{ secrets.TOKEN_SECRET }}
      - name: pull-arm64
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 5
          retry_wait_seconds: 60
          max_attempts: 6
          command: docker pull ghcr.io/amrutprabhu/home-assistant:$GITHUB_REF_NAME-aarch_64
      - name: create-manifest
        run: |
          docker manifest create ghcr.io/amrutprabhu/home-assistant:$GITHUB_REF_NAME --amend ghcr.io/amrutprabhu/home-assistant:$GITHUB_REF_NAME-x86_64 --amend ghcr.io/amrutprabhu/home-assistant:$GITHUB_REF_NAME-aarch_64
          docker manifest push ghcr.io/amrutprabhu/home-assistant:$GITHUB_REF_NAME
#          docker manifest create ghcr.io/amrutprabhu/home-assistant:latest --amend ghcr.io/amrutprabhu/home-assistant:$GITHUB_REF_NAME-x86_64 --amend ghcr.io/amrutprabhu/home-assistant:$GITHUB_REF_NAME-aarch_64
#          docker manifest push ghcr.io/amrutprabhu/home-assistant:latest